# Streamlit Secrets Configuration
# This file provides fallback configuration for the Meghalaya Tourism Bot
# Replace the placeholder values with your actual credentials

[mongodb]
uri = "your_mongodb_connection_string_here"
database = "meghalaya_tourism"
collection = "tourism_documents"

[openai]
api_key = "your_openai_api_key_here"
model = "gpt-4"
embedding_model = "text-embedding-3-large"

[retrieval]
top_k_documents = 5
temperature = 0.7
max_tokens = 1000
